version: '3.10'
services:
  django:
    build: 
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile name if it's not named 'Dockerfile'
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    container_name: my_first_django_container

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/django/cert.pem
      - ./key.pem:/django/key.pem
    ports:
      - "443:443"